package androidx.gridlayout;

public final class R {

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 2131100008;
        public static final int compat_button_inset_vertical_material = 2131100009;
        public static final int compat_button_padding_horizontal_material = 2131100010;
        public static final int compat_button_padding_vertical_material = 2131100011;
        public static final int compat_control_corner_material = 2131100012;
        public static final int compat_notification_large_icon_max_height = 2131100013;
        public static final int compat_notification_large_icon_max_width = 2131100014;
        public static final int default_gap = 2131100053;
        public static final int notification_action_icon_size = 2131100674;
        public static final int notification_action_text_size = 2131100675;
        public static final int notification_big_circle_margin = 2131100676;
        public static final int notification_content_margin_start = 2131100677;
        public static final int notification_large_icon_height = 2131100678;
        public static final int notification_large_icon_width = 2131100679;
        public static final int notification_main_column_padding_top = 2131100680;
        public static final int notification_media_narrow_margin = 2131100681;
        public static final int notification_right_icon_size = 2131100682;
        public static final int notification_right_side_padding_top = 2131100683;
        public static final int notification_small_icon_background_padding = 2131100684;
        public static final int notification_small_icon_size_as_large = 2131100685;
        public static final int notification_subtext_size = 2131100686;
        public static final int notification_top_pad = 2131100687;
        public static final int notification_top_pad_large_text = 2131100688;
    }

    public static final class styleable {
        public static final int[] ColorStateListItem = {16843173, 16843551, com.miui.gallery.R.attr.alpha};
        public static final int ColorStateListItem_alpha = 2;
        public static final int ColorStateListItem_android_alpha = 1;
        public static final int ColorStateListItem_android_color = 0;
        public static final int[] CoordinatorLayout = {com.miui.gallery.R.attr.keylines, com.miui.gallery.R.attr.statusBarBackground};
        public static final int[] CoordinatorLayout_Layout = {16842931, com.miui.gallery.R.attr.layout_anchor, com.miui.gallery.R.attr.layout_anchorGravity, com.miui.gallery.R.attr.layout_behavior, com.miui.gallery.R.attr.layout_dodgeInsetEdges, com.miui.gallery.R.attr.layout_insetEdge, com.miui.gallery.R.attr.layout_keyline};
        public static final int CoordinatorLayout_Layout_android_layout_gravity = 0;
        public static final int CoordinatorLayout_Layout_layout_anchor = 1;
        public static final int CoordinatorLayout_Layout_layout_anchorGravity = 2;
        public static final int CoordinatorLayout_Layout_layout_behavior = 3;
        public static final int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
        public static final int CoordinatorLayout_Layout_layout_insetEdge = 5;
        public static final int CoordinatorLayout_Layout_layout_keyline = 6;
        public static final int CoordinatorLayout_keylines = 0;
        public static final int CoordinatorLayout_statusBarBackground = 1;
        public static final int[] FontFamily = {com.miui.gallery.R.attr.fontProviderAuthority, com.miui.gallery.R.attr.fontProviderCerts, com.miui.gallery.R.attr.fontProviderFetchStrategy, com.miui.gallery.R.attr.fontProviderFetchTimeout, com.miui.gallery.R.attr.fontProviderPackage, com.miui.gallery.R.attr.fontProviderQuery};
        public static final int[] FontFamilyFont = {16844082, 16844083, 16844095, 16844143, 16844144, com.miui.gallery.R.attr.font, com.miui.gallery.R.attr.fontStyle, com.miui.gallery.R.attr.fontVariationSettings, com.miui.gallery.R.attr.fontWeight, com.miui.gallery.R.attr.ttcIndex};
        public static final int FontFamilyFont_android_font = 0;
        public static final int FontFamilyFont_android_fontStyle = 2;
        public static final int FontFamilyFont_android_fontVariationSettings = 4;
        public static final int FontFamilyFont_android_fontWeight = 1;
        public static final int FontFamilyFont_android_ttcIndex = 3;
        public static final int FontFamilyFont_font = 5;
        public static final int FontFamilyFont_fontStyle = 6;
        public static final int FontFamilyFont_fontVariationSettings = 7;
        public static final int FontFamilyFont_fontWeight = 8;
        public static final int FontFamilyFont_ttcIndex = 9;
        public static final int FontFamily_fontProviderAuthority = 0;
        public static final int FontFamily_fontProviderCerts = 1;
        public static final int FontFamily_fontProviderFetchStrategy = 2;
        public static final int FontFamily_fontProviderFetchTimeout = 3;
        public static final int FontFamily_fontProviderPackage = 4;
        public static final int FontFamily_fontProviderQuery = 5;
        public static final int[] GradientColor = {16843165, 16843166, 16843169, 16843170, 16843171, 16843172, 16843265, 16843275, 16844048, 16844049, 16844050, 16844051};
        public static final int[] GradientColorItem = {16843173, 16844052};
        public static final int GradientColorItem_android_color = 0;
        public static final int GradientColorItem_android_offset = 1;
        public static final int GradientColor_android_centerColor = 7;
        public static final int GradientColor_android_centerX = 3;
        public static final int GradientColor_android_centerY = 4;
        public static final int GradientColor_android_endColor = 1;
        public static final int GradientColor_android_endX = 10;
        public static final int GradientColor_android_endY = 11;
        public static final int GradientColor_android_gradientRadius = 5;
        public static final int GradientColor_android_startColor = 0;
        public static final int GradientColor_android_startX = 8;
        public static final int GradientColor_android_startY = 9;
        public static final int GradientColor_android_tileMode = 6;
        public static final int GradientColor_android_type = 2;
        public static final int[] GridLayout = {com.miui.gallery.R.attr.alignmentMode, com.miui.gallery.R.attr.columnCount, com.miui.gallery.R.attr.columnOrderPreserved, com.miui.gallery.R.attr.orientation, com.miui.gallery.R.attr.rowCount, com.miui.gallery.R.attr.rowOrderPreserved, com.miui.gallery.R.attr.useDefaultMargins};
        public static final int[] GridLayout_Layout = {16842996, 16842997, 16842998, 16842999, 16843000, 16843001, 16843002, com.miui.gallery.R.attr.layout_column, com.miui.gallery.R.attr.layout_columnSpan, com.miui.gallery.R.attr.layout_columnWeight, com.miui.gallery.R.attr.layout_gravity, com.miui.gallery.R.attr.layout_row, com.miui.gallery.R.attr.layout_rowSpan, com.miui.gallery.R.attr.layout_rowWeight};
        public static final int GridLayout_Layout_android_layout_height = 1;
        public static final int GridLayout_Layout_android_layout_margin = 2;
        public static final int GridLayout_Layout_android_layout_marginBottom = 6;
        public static final int GridLayout_Layout_android_layout_marginLeft = 3;
        public static final int GridLayout_Layout_android_layout_marginRight = 5;
        public static final int GridLayout_Layout_android_layout_marginTop = 4;
        public static final int GridLayout_Layout_android_layout_width = 0;
        public static final int GridLayout_Layout_layout_column = 7;
        public static final int GridLayout_Layout_layout_columnSpan = 8;
        public static final int GridLayout_Layout_layout_columnWeight = 9;
        public static final int GridLayout_Layout_layout_gravity = 10;
        public static final int GridLayout_Layout_layout_row = 11;
        public static final int GridLayout_Layout_layout_rowSpan = 12;
        public static final int GridLayout_Layout_layout_rowWeight = 13;
        public static final int GridLayout_alignmentMode = 0;
        public static final int GridLayout_columnCount = 1;
        public static final int GridLayout_columnOrderPreserved = 2;
        public static final int GridLayout_orientation = 3;
        public static final int GridLayout_rowCount = 4;
        public static final int GridLayout_rowOrderPreserved = 5;
        public static final int GridLayout_useDefaultMargins = 6;
    }
}
